FROM python:3.12

WORKDIR /app

COPY app/requirements.txt .

RUN pip install torch --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .
COPY run.py .

ENV FLASK_APP=run.py
ENV FLASK_ENV=development

EXPOSE 5000

CMD ["python", "run.py"]